name: Build & Deploy
on:
  push:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
      - name: Run E2E tests
        working-directory: ./api
        run: npm run test:e2e
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-list:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@master
        with:
          repository: wayn3r/todo-list-argocd
          ref: master
          token: ${{ secrets.TOKEN }}
      - name: Setup Git Author config
        run: /
          git config --global user.email w9delacruz@gmail.com
          git config --global user.name wayn3r
          sed -i "s-${{ github.actor }}.*-${{ github.actor }}/todo-list:${{ github.sha }}-g" todo-list/deployment.yaml
          git add todo-list/deployment.yaml
          git commit -m "deploy(todo-list) update deployment with tag ${{ github.sha }}"
      - name: Publish changes
        run: git push origin master