name: Build, Deploy & Preview
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
      - name: Run E2E tests
        working-directory: ./api
        run: npm run test:e2e
  build_and_push_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-preview:${{ github.event.pull_request.head.sha }}
  add_preview_label:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: |
          preview
