name: Clean Up Preview Application files
on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@master
        with:
          repository: wayn3r/todo-list-argocd
          ref: master
          token: ${{ secrets.TOKEN }}
      - name: Clean Up Review Application
        run: |
          git config --global user.email w9delacruz@gmail.com
          git config --global user.name wayn3r
          export branch_slug=$(echo ${{ github.head_ref }} | sed 's./.-.')
          rm -rf todo-list-previews/$branch_slug
          git add todo-list-previews/$branch_slug
          git commit -m "clean(todo-list-preview) remove $branch_slug"
      - name: Publish changes
        run: git push origin master
  
