name: Clean Up Preview Application files
on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@master
        with:
          repository: wayn3r/todo-list-argocd
          ref: master
          token: ${{ secrets.TOKEN }}
      - name: Clean Up Review Application && Publish changes
        run: |
          git config --global user.email w9delacruz@gmail.com
          git config --global user.name wayn3r
          if(rm -r todo-list-previews/${{ github.event.number }}); 
          then 
            git add todo-list-previews/${{ github.event.number }}
            git commit -m "wipe(todo-list-preview) remove #${{ github.event.number }} ${{ github.head_ref }}"
            git push origin master
          else 
            echo 'Pull request #${{ github.event.number }} had no preview deployments'; 
          fi;

  
